### ISSUE TITLE
Cannot unmarshal object into Go struct field IngressSpec.spec.rules of type []v1.IngressRule

### ISSUE THREAD

**Issue by nileshbhope-indusface** [openclarity/apiclarity#304]
#### What happened:

While configuring kong gateway with apiclarity using steps given at
https://github.com/openclarity/apiclarity/tree/master/plugins/gateway/kong.

I have started sock shop demo on ubuntu 22 machine. And able to see traffic from sock shock
getting reflected in Api clarity. So this setup is done properly. After executing
kubectl apply -f https://bit.ly/kong-ingress-dbless successfully.

While Configure Ingress: I am getting below error,
Cannot unmarshal object into Go struct field IngressSpec.spec.rules of type []v1.IngressRule

#### What you expected to happen:
It should have applied as per steps given.

#### How to reproduce it (as minimally and precisely as possible):
Follow steps given at https://github.com/openclarity/apiclarity/tree/master/plugins/gateway/kong

Below yaml setting I used to configure ingress as per compatible apiVersion: networking.k8s.io/v1

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catalogue
  namespace: sock-shop
spec:
  ingressClassName: kong
  rules:
    http:
      paths:
        - path: /
      pathType: Prefix
      backend:
        service:
          name: catalogue
          port:
            number: 80
```

#### Are there any error messages in API Clarity logs?
(e.g. `kubectl logs -n apiclarity --selector=app=apiclarity`)

#### Environment:
- Kubernetes version (use `kubectl version --short`):
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.25.3

- Istio version (use `istioctl version`):
none
- APIClarity version (use `kubectl -n apiclarity exec deploy/apiclarity -- ./backend version`)
latest from repo
- Cloud provider or hardware configuration:
- Others:
